title: Advanced OOP Course Documentation
description: Comprehensive Java Advanced Object-Oriented Programming course documentation
author: Sifat Ali
email: your-email@example.com
baseurl: ""
url: "https://sifatali008.github.io/Practice-AOOP-With-Sifat"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 