name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm install -g markdown-pdf
        npm install -g markdown-it
        
    - name: Build Documentation
      run: |
        echo "Building documentation..."
        # Convert markdown to HTML for better viewing
        markdown-it Advanced_OOP_Documentation.md > docs/index.html
        markdown-it Week1_Learning_README.md > docs/week1.html
        markdown-it README.md > docs/home.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs 